version: 2
updates:
  # Enable version updates for pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    # No reviewers or assignees for automated dependency updates
    # The Dependabot Auto-Merge workflow will handle approval automatically
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for test dependencies
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    # No reviewers or assignees for automated dependency updates
    # The Dependabot Auto-Merge workflow will handle approval automatically
    commit-message:
      prefix: "pip-tests"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "tests"
    groups:
      test-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      test-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    # No reviewers or assignees for automated dependency updates
    # The Dependabot Auto-Merge workflow will handle approval automatically
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    # No reviewers or assignees for automated dependency updates
    # The Dependabot Auto-Merge workflow will handle approval automatically
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
